# Generated by Django 6.0.3 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
